# Generated by Django 5.1.5 on 2025-08-06 16:49

import django.db.models.deletion
import django.utils.timezone
import referral_service.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=referral_service.models.generate_referral_code, max_length=20, unique=True)),
                ('code_type', models.CharField(choices=[('user', 'User Generated'), ('campaign', 'Campaign Code'), ('admin', 'Admin Generated')], default='user', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('total_registrations', models.PositiveIntegerField(default=0)),
                ('total_verified_users', models.PositiveIntegerField(default=0)),
                ('total_paying_users', models.PositiveIntegerField(default=0)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referral_codes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_limit', models.PositiveIntegerField(default=10)),
                ('weekly_limit', models.PositiveIntegerField(default=50)),
                ('monthly_limit', models.PositiveIntegerField(default=200)),
                ('total_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_used', models.PositiveIntegerField(default=0)),
                ('weekly_used', models.PositiveIntegerField(default=0)),
                ('monthly_used', models.PositiveIntegerField(default=0)),
                ('total_used', models.PositiveIntegerField(default=0)),
                ('daily_reset_at', models.DateTimeField(auto_now_add=True)),
                ('weekly_reset_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_reset_at', models.DateTimeField(auto_now_add=True)),
                ('successful_referrals', models.PositiveIntegerField(default=0)),
                ('verified_referrals', models.PositiveIntegerField(default=0)),
                ('paying_referrals', models.PositiveIntegerField(default=0)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLimitHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_daily', models.PositiveIntegerField()),
                ('previous_weekly', models.PositiveIntegerField()),
                ('previous_monthly', models.PositiveIntegerField()),
                ('previous_total', models.PositiveIntegerField(blank=True, null=True)),
                ('new_daily', models.PositiveIntegerField()),
                ('new_weekly', models.PositiveIntegerField()),
                ('new_monthly', models.PositiveIntegerField()),
                ('new_total', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('set', 'Set Absolute'), ('increase', 'Increased'), ('decrease', 'Decreased'), ('boost', 'Temporary Boost'), ('disable', 'Disabled'), ('resume', 'Resumed')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_limit_history_changes', to=settings.AUTH_USER_MODEL)),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='referral_service.referrallimit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rewarded', 'Rewarded'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('user_verified_at', models.DateTimeField(blank=True, null=True)),
                ('first_payment_at', models.DateTimeField(blank=True, null=True)),
                ('first_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('registration_device_type', models.CharField(blank=True, max_length=20)),
                ('days_to_verify', models.PositiveIntegerField(blank=True, null=True)),
                ('days_to_first_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('referrer_rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user_rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='referral_service.referralcode')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('code_generated', 'Referral Code Generated'), ('code_shared', 'Referral Code Shared'), ('registration_started', 'Registration Started'), ('registration_completed', 'Registration Completed'), ('email_verified', 'Email Verified'), ('first_payment', 'First Payment Made'), ('reward_given', 'Reward Given'), ('limit_reached', 'Limit Reached'), ('code_expired', 'Code Expired')], max_length=25)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referral_service.referralcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to=settings.AUTH_USER_MODEL)),
                ('referral_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referral_service.referralrelationship')),
            ],
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='referral_se_code_495638_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['owner'], name='referral_se_owner_i_a2a6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code_type'], name='referral_se_code_ty_0280fa_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['status'], name='referral_se_status_fda55d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['created_at'], name='referral_se_created_32a2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['last_used_at'], name='referral_se_last_us_613006_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit__isnull', True), ('usage_limit__gte', 0), _connector='OR'), name='valid_usage_limit'),
        ),
        migrations.AddIndex(
            model_name='referrallimit',
            index=models.Index(fields=['user'], name='referral_se_user_id_5e41a7_idx'),
        ),
        migrations.AddIndex(
            model_name='referrallimit',
            index=models.Index(fields=['is_suspended'], name='referral_se_is_susp_c5149d_idx'),
        ),
        migrations.AddIndex(
            model_name='referrallimit',
            index=models.Index(fields=['daily_reset_at'], name='referral_se_daily_r_21d50a_idx'),
        ),
        migrations.AddIndex(
            model_name='referrallimit',
            index=models.Index(fields=['weekly_reset_at'], name='referral_se_weekly__baffa7_idx'),
        ),
        migrations.AddIndex(
            model_name='referrallimit',
            index=models.Index(fields=['monthly_reset_at'], name='referral_se_monthly_945030_idx'),
        ),
        migrations.AddIndex(
            model_name='referrallimithistory',
            index=models.Index(fields=['limit', 'action', 'created_at'], name='referral_se_limit_i_170739_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrelationship',
            index=models.Index(fields=['referrer'], name='referral_se_referre_c82d26_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrelationship',
            index=models.Index(fields=['referred_user'], name='referral_se_referre_8a0910_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrelationship',
            index=models.Index(fields=['referral_code_used'], name='referral_se_referra_8f262a_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrelationship',
            index=models.Index(fields=['status'], name='referral_se_status_d81abf_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrelationship',
            index=models.Index(fields=['created_at'], name='referral_se_created_36022d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrelationship',
            index=models.Index(fields=['user_verified_at'], name='referral_se_user_ve_e1c9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrelationship',
            index=models.Index(fields=['first_payment_at'], name='referral_se_first_p_1ec0ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralrelationship',
            constraint=models.UniqueConstraint(fields=('referred_user',), name='unique_referral_per_user'),
        ),
        migrations.AddConstraint(
            model_name='referralrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('referrer', models.F('referred_user')), _negated=True), name='no_self_referral'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['event_type'], name='referral_se_event_t_6e3c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['user'], name='referral_se_user_id_a072f0_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['referral_code'], name='referral_se_referra_d4d2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['created_at'], name='referral_se_created_f42115_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['event_type', 'created_at'], name='referral_se_event_t_1c606c_idx'),
        ),
    ]
