# Generated by Django 5.1.5 on 2025-09-10 19:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import referral_service.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Referral Settings',
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=referral_service.models.generate_referral_code, max_length=20, unique=True)),
                ('code_type', models.CharField(choices=[('user', 'User Generated'), ('campaign', 'Campaign Code')], default='user', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('max_usage', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('reward_calls', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('reward_calls_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reward_given_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='referral_service.referralcode')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='referral_se_code_495638_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['owner'], name='referral_se_owner_i_a2a6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code_type'], name='referral_se_code_ty_0280fa_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['status'], name='referral_se_status_fda55d_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralrelationship',
            constraint=models.UniqueConstraint(fields=('referred_user',), name='unique_referral_per_user'),
        ),
    ]
