# Generated by Django 5.1.5 on 2025-08-06 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('call_type', models.CharField(default='audio', max_length=20)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('initiated', 'Initiated'), ('incoming', 'Incoming'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('busy', 'Busy'), ('canceled', 'Canceled'), ('missed', 'Missed'), ('ended', 'Ended')], default='initiated', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('was_connected', models.BooleanField(default=False)),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee_calls', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
