# Generated by Django 5.1.5 on 2025-09-06 10:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio Call'), ('video', 'Video Call')], default='audio', max_length=20)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('busy', 'Busy'), ('canceled', 'Canceled'), ('missed', 'Missed'), ('ended', 'Ended'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('previous_state', models.CharField(blank=True, max_length=20, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ringing_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('ring_duration', models.IntegerField(blank=True, default=0, help_text='Time from ring to answer/reject (ms)', null=True)),
                ('response_time', models.IntegerField(blank=True, default=0, help_text='Time from initiation to answer/reject (ms)', null=True)),
                ('inviter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('invitee_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('inviter_device', models.CharField(blank=True, max_length=200)),
                ('invitee_device', models.CharField(blank=True, max_length=200)),
                ('was_connected', models.BooleanField(default=False)),
                ('call_quality_rating', models.FloatField(blank=True, help_text='Average rating from participants', null=True)),
                ('inviter_rating', models.FloatField(blank=True, null=True)),
                ('invitee_rating', models.FloatField(blank=True, null=True)),
                ('inviter_feedback', models.TextField(blank=True)),
                ('invitee_feedback', models.TextField(blank=True)),
                ('call_cost', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('deducted_from_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deducted_from_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduction_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='call_service.callrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['call_id'], name='call_servic_call_id_8295a8_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['inviter', 'initiated_at'], name='call_servic_inviter_7e6985_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['invitee', 'initiated_at'], name='call_servic_invitee_34331d_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['state'], name='call_servic_state_273e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['initiated_at'], name='call_servic_initiat_d328f6_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['deduction_status'], name='call_servic_deducti_08f5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='calleventlog',
            index=models.Index(fields=['call', 'timestamp'], name='call_servic_call_id_785a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='calleventlog',
            index=models.Index(fields=['event_type'], name='call_servic_event_t_ff2860_idx'),
        ),
    ]
