# Generated by Django 5.1.5 on 2025-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_service', '0001_schedule_celery_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='call-778112f6', max_length=255, unique=True),
        ),
    ]
