# Generated by Django 5.1.5 on 2025-03-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_service', '0002_alter_call_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='call-b50374d6', max_length=255, unique=True),
        ),
    ]
